root: true

env:
  node: true

extends:
  - eslint:recommended
  - next/core-web-vitals
  - prettier

overrides:
  - files: ['**/*.js']
    excludedFiles: [test, jest-setup.js]
    extends: [./node_modules/cpp-infra-util/.eslintrc.js.yml, prettier]

  - files: [jest-setup.js]
    extends: [./node_modules/cpp-infra-util/.eslintrc.js.yml, prettier]
    parserOptions:
      sourceType: module
      ecmaFeatures:
        jsx: true

  - files: ['**/*.ts', '**/*.tsx']
    excludedFiles: [test, '**/*.spec.ts', '**/*.spec.tsx']
    extends: [./.eslintrc.ts.yml, prettier]

  - files: ['test/**/*.ts', '**/*.spec.ts', '**/*.spec.tsx']
    extends: [./.eslintrc.ts.yml, ./node_modules/cpp-infra-util/.eslintrc.jest.yml, prettier]
