version: '3.9'

networks:
  cpp-ui-network:
    name: cpp-ui-network

services:
  ui:
    build: ./
    command: sh -cx "rm -rf '/app/.next/*' ; yarn run next build && yarn run next start -p 3001"
    networks:
      - cpp-ui-network
    ports:
      - 3001:3001
    volumes:
      - ./:/app:ro
      - ui_next:/app/.next

  cypress:
    depends_on:
      - ui
    image: public.ecr.aws/o8c0q7c2/cpp-cypress:v1.0.3
    environment:
      - CYPRESS_BASE_URL=http://ui:3001
      - DISPLAY
      - HOST_UID
      - HOST_GID
    networks:
      - cpp-ui-network
    profiles: [integration]
    volumes:
      - ./artifacts/cypress:/app/artifacts/cypress
      - ./cypress:/app/cypress
      - cypress_chrome:/opt/google
      - cypress_edge:/opt/microsoft
      - cypress_firefox:/opt/firefox

volumes:
  # Persist the .next folder to speed up builds.
  ui_next:

  # Persist some browser folders to accommodate auto-update behavior.
  cypress_chrome:
  cypress_edge:
  cypress_firefox:
