export const options = [
  { label: 'Additional Deposit Required', value: 'Additional Deposit Required' },
  { label: 'Applicant Did Not Provide Documents', value: 'Applicant Did Not Provide Documents' },
  { label: 'Applicant Unresponsive', value: 'Applicant Unresponsive' },
  { label: 'Application Transfer', value: 'Application Transfer' },
  { label: 'Applied Sight Unseen – Ready', value: 'Applied Sight Unseen – Ready' },
  { label: 'Chose A Non-Progress Home', value: 'Chose A Non-Progress Home' },
  { label: 'COVID-19', value: 'COVID-19' },
  { label: 'Deployment/Military', value: 'Deployment/Military' },
  { label: 'Employment Status Change', value: 'Employment Status Change' },
  { label: 'Existing Home Sale Fell Through', value: 'Existing Home Sale Fell Through' },
  { label: 'Fraud', value: 'Fraud' },
  { label: 'HOA Approval/Delays', value: 'HOA Approval/Delays' },
  { label: 'Holding Period Expired', value: 'Holding Period Expired' },
  { label: 'Home To Home Transfer', value: 'Home To Home Transfer' },
  { label: 'Housing Authority', value: 'Housing Authority' },
  { label: 'Lack Of Amenity', value: 'Lack Of Amenity' },
  { label: 'Lease Terms', value: 'Lease Terms' },
  { label: 'NSF', value: 'NSF' },
  { label: 'NTV Cancellation', value: 'NTV Cancellation' },
  { label: 'Pre-Lease -Did not Approve of', value: 'Pre-Lease -Did not Approve of' },
  { label: 'Pre-lease Pending Alt Choice', value: 'Pre-lease Pending Alt Choice' },
  { label: 'School District', value: 'School District' },
  { label: 'Unable to Verify ID', value: 'Unable to Verify ID' },
  { label: 'Unexpected RR Delay', value: 'Unexpected RR Delay' },
  { label: 'Utilities', value: 'Utilities' },
];
